### PR TITLE
Add electron-tabs

### PR DESCRIPTION
**Pull request by brrd**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

Simply create and manage tab components which use webviews: https://github.com/brrd/electron-tabs

### CODE REVIEW

**Comment by parro-it** [comment]
Looks great :clap:

**Comment by sindresorhus** [comment]
Why is it tied to Electron? Doesn't look like you're using any Electron specific APIs.

---

Some feedback:
- It should come with a demo app or a preview on `gh-pages`, so people can try it out.
- Would have been nice if drag-drop support was built-in. Size doesn't matter for that much for apps, so you could just depend on Dragula yourself. It's nice when modules *just work*, without any extra chore.
- The readme screenshot is blurry on High-DPI screens.
- The default tab style could be better. The favicon, title, and close button are all horizontally unaligned.
- Would be awesome if it shipped with native like style for each platform. On macOS for example, it could borrow the CSS from https://github.com/leo/hyper-native (This style also looks nice: https://github.com/insanityfarm/hyperterm-mactabs)
- The readme usage example shows using `visible: true`, but that's already the default and moot.

**Comment by brrd** [comment]
Hi, thanks for your feedback,

> Why is it tied to Electron? Doesn't look like you're using any Electron specific APIs.

Hmm... webviews?

> * It should come with a demo app or a preview on gh-pages, so people can try it out.

I'm pretty sure this won't work in browsers. This module uses webviews (from Electron), EventEmitter (from Node) and some ES6 features which are not supported yet in most browsers.

> * Would have been nice if drag-drop support was built-in. Size doesn't matter for that much for apps, so you could just depend on Dragula yourself. It's nice when modules just work, without any extra chore.
> * The default tab style could be better. The favicon, title, and close button are all horizontally unaligned.
> * Would be awesome if it shipped with native like style for each platform. On macOS for example, it could borrow the CSS from https://github.com/leo/hyper-native (This style also looks nice: https://github.com/insanityfarm/hyperterm-mactabs)

This module purpose is to provide simple API to handle tabs/webviews in electron. Full stop. 

In my opinion developers should write their own styles and UI to match their app appearance, this is why I don't force anything in term of UI. Actually at the very beginning this module was not even supposed to provide UI things such as CSS, animations and fancy drag and drop. But I anticipated users would ask for it, so I added some basic CSS (which is actually called "the sample electron-tabs stylesheet" in the documentation) and dragula compatibility. 

To be clear: these are great ideas which could be added in future (I'm gonna think about it), for sure, but in my opinion this is out of electron-tabs main purpose. And contributions are welcome!

> * The readme screenshot is blurry on High-DPI screens.

I've seen that 😕 I could use a bigger image to let the browser do the reduction but... maybe you know a better way to fix this?

> * Per the contribution guidelines: "Submitted packages should be tested and documented."

Well, I'm planning to do this, but I'm pretty sure it will take more time to write tests for this than it took to create the module itself and I'm quite busy right now...
Should we keep this PR open until tests are written?

**Comment by sindresorhus** [comment]
> Hmm... webviews?

https://developer.chrome.com/apps/tags/webview
http://docs.nwjs.io/en/latest/References/webview%20Tag/

But my point is that you've pretty much just created a generic tab component that happens to change one attribute on a `<webview>` tag, that could easily have been a different HTML tag. This somehow feels like all the jQuery plugins that were just wrapper plugins because jQuery.

I understand you want focus. I'm just sad about the code waste. Someday someone using NW.js will waste time recreating this.

> I'm pretty sure this won't work in browsers. This module uses webviews (from Electron), EventEmitter (from Node) and some ES6 features which are not supported yet in most browsers.

Demo app then.

> In my opinion developers should write their own styles and UI to match their app appearance

This is one of the reasons I often hear why people dread Electron apps. Everyone does their own UI badly. Chrome (no not the browser) UI like that should IMHO match the system. Apps are not websites. Of course people should be able to create their own, but having a good default is essential.

> I've seen that 😕 I could use a bigger image to let the browser do the reduction but... maybe you know a better way to fix this?

You just set the width to half the actual size of the image. See: https://github.com/sindresorhus/ama/issues/428

> Should we keep this PR open until tests are written?

Nah. I don't like stale PRs. We can reopen this when demo app and tests are written.

**Pull request closed without merging**
