### PR TITLE
Added Electrojet to Boilerplates section : A no-hassle foundation for Electron apps that lets you take off quickly 🚀

### PR DESCRIPTION
**Pull request by o-my-code**
[ElectroJet](https://github.com/vinaychandranvs/electrojet) is a set of easy-to-use, ready-to-go boilerplates for Electron!

So, what all stuff are there?
Electron and React are available by default in all boilerplates.

**Along with them, you can have:** 

- Redux
- React Router
- Connected React Router
- Redux Persist
- Electron Store

**Build tools:**

- Webpack
- Babel

**Other stuff**

- ESlint based on Standard JS
- React PropTypes
- Auto reloading main process with Chokidar
- Support for Decorators

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
> There are lots of boilerplates which pack a crazy ton of shit.

Yours does too though.

**Comment by sindresorhus** [comment]
I'm very wary of adding boilerplates as every time I do, they end up being unmaintained after a while.

**Comment by sindresorhus** [comment]
You want to remove hassle, but you chose to use `electron-packager` instead of `electron-builder`. `electron-packager` only solves a minor bit of everything involved in building and packaging an app.

**Comment by o-my-code** [comment]
@sindresorhus 
1. Yes, it does have a lot of things. But the difference is, the user can choose what they want. They can go with a minimal boilerplate or a fully fledged one.

2. I intend to maintain it as necessary. 

3. I wasn't completely aware of the differences as I used to always use `electron-packager`. I will look into it. 

Thank you for reviewing.

**Pull request closed without merging**
