### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by cemolcay**
[Gif maker](http://gifmaker.io) added.
Great and userfriendly tool for creating gifs from videos

### CODE REVIEW

**Comment by shinnn** [comment]
https://github.com/sindresorhus/awesome-electron/blob/d09b6b9c663355b9f4c68cfc0ba741387f04bfcd/contributing.md

**Comment by tehbilly** [comment]
@shinnn What's the PR missing? I read over the linked document and this one appears to adhere to those!

**Comment by sindresorhus** [comment]
@tehbilly Multiple things. Read it again.

**Comment by sindresorhus** [comment]
The merge conflict also needs to be resolved.

*(Don't open a new PR, just fix it in this one).*

**Comment by tehbilly** [comment]
I'm asking as a completely unrelated third party out of curiosity. I have no vested interest in this PR in particular, but rather am unclear which parts of the guidelines it violates.

The tone of *"Thank you for your suggestions"* and using the word "guidelines" is bit at odds with canned-response pasting of a link and no explanation. It's hard to put inflection into text, but the second response comes across as *"well obviously you can't read, because there's *multiple* things wrong, so try again"*.

**Comment by seangarner** [comment]
Hey @tehbilly, I'd try not to read into the tone.  It may just be somebody economising on how long it takes to reply.  As for the guidelines, I spotted these problems:

> Start the description with a capital and end with a full stop/period.

> The pull request should have a useful title

Also the commit message is "Update readme.md" which if you check https://github.com/sindresorhus/awesome-electron/commits is probably never allowed.  Don't see that in the guidelines though.

**Comment by sindresorhus** [comment]
Closing for lack of response by OP.

**Pull request closed without merging**
