### PR TITLE
add Wire

### PR DESCRIPTION
**Pull request by herrmannplatz**

### CODE REVIEW

**Comment by bennyn** [comment]
Very nice and beautiful example for the usage of Electron! :+1:

**Comment by gregor** [comment]
:+1:

**Comment by shinnn** [comment]
https://github.com/sindresorhus/awesome-electron/blob/d09b6b9c663355b9f4c68cfc0ba741387f04bfcd/contributing.md

**Comment by lipis** [comment]
screen shot 2015-10-29 at 13 28 30

(also we work for Wire)

**Comment by herrmannplatz** [comment]
You can download windows or mac app to verify. https://wire.com/download/

**Comment by sindresorhus** [comment]
Looks beautiful :)

**Pull request closed without merging**
