### PR TITLE
Add Platmatic

### PR DESCRIPTION
**Pull request by el-davo**
https://github.com/el-davo/platmatic A desktop application for interacting with PAAS systems

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by el-davo** [comment]
Closing as no comments or feedback. I can only assume awesome-electron is no longer maintained

**Comment by wattengard** [comment]
How passive agressive of you...

**Comment by willyb321** [comment]
lol

**Comment by jdfwarrior** [comment]
Or that people may have been busy. How dare they not stop what they are doing and take care of him right that second while doing all this for free.

**Comment by el-davo** [comment]
My Apologies. Comment removed. Thanks for the feedback

**Pull request closed without merging**
