### PR TITLE
Add electron-require

### PR DESCRIPTION
**Pull request by brrd**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not a big fan of this myself. Too much magic. I prefer the explicitness of normal require.

**Comment by zeke** [comment]
I had a feeling @sindresorhus would reject this! 

I agree that it's a bit magic, but I appreciate the sentiment: don't make me refer to the docs every time I want to require something.

**Comment by sindresorhus** [comment]
@zeke I didn't reject this. Look at the merge.

**Comment by zeke** [comment]
Oh ha. I saw the 🚫 and thought the worst.

**Pull request closed without merging**
