### PR TITLE
Add Yays! app

### PR DESCRIPTION
**Pull request by Bahlaouane-Hamza**
Yays! allows you to collect & play your favorite youtube music links in one place, this way you will gain more space in your browser.

Thank you for the awesome list :+1:

### CODE REVIEW

**Comment by sindresorhus** [comment]
You should add binaries so users can just double-click and run the app. It's currently too hard to get started. Can easily be achieved with electron-packager.

**Comment by Bahlaouane-Hamza** [comment]
Thank you @sindresorhus for letting me know. Great stuff, i did create a release for it, should I resubmit my PR?

**Comment by sindresorhus** [comment]
Uhm, it was already merged.

**Comment by Bahlaouane-Hamza** [comment]
Ah, my bad, Thanks.

**Pull request closed without merging**
