### PR TITLE
Adding API Garage as a closed source app.

### PR DESCRIPTION
**Pull request by apigarage**
For evidence, please check the download page for API Garage. http://www.apigarage.com/download.html

### CODE REVIEW

**Comment by shinnn** [comment]
> @apigarage 

I recommend to register @apigarage as an organization account.

> For evidence

What kind of *evidence* does the page provide?

> http://www.apigarage.com/download.html

The link doesn't seem to be linked from any other pages.

What is more, though I downloaded the OS X binary and doubleclicked the app, nothing happened.

**Comment by shinnn** [comment]
And you're missing some of the contribution guidelines. https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md#contribution-guidelines

**Comment by arthurvr** [comment]
ping @apigarage :)

**Comment by apigarage** [comment]
Sorry for the delay. Some of the team members are not in favour of publishing the technology, yet. Will redo the pull request when I have all the team members on board. 

Keep up the good work :).

**Pull request closed without merging**
