### PR TITLE
Add Markn app

### PR DESCRIPTION
**Pull request by xHN35RQ**
:cake:

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

**Comment by xHN35RQ** [comment]
oops, forgot the period. :disappointed:

**Comment by xHN35RQ** [comment]
oops, forgot the period. :disappointed:

**Comment by sindresorhus** [comment]
No need to open a new PR. That just litters up the issue tracker... Next time just update the existing one.

**Comment by xHN35RQ** [comment]
Yep sorry. I messed up the other PR by being stupid with my local git repo. thanks.

**Pull request closed without merging**
