### PR TITLE
Add electron-sudo

### PR DESCRIPTION
**Pull request by automation-stack**
Electron subprocesses with administrative privileges and prompting OS dialog if necessary.

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

**Comment by automation-stack** [comment]
@sindresorhus please specify what is wrong?

**Comment by parro-it** [comment]
* Additions should be added to the bottom of the relevant section.

**Comment by sindresorhus** [comment]
@automation-stack Don't take this the wrong way, but it's pretty annoying as a maintainer to spend lots of time crafting a good contributing.md and then have no one read or follow it, even when pointed out.

**Comment by automation-stack** [comment]
@sindresorhus I read contributing.md completely, of course, before doing PR, I apologize for inattention to detail, I'll fix it

**Comment by sindresorhus** [comment]
@automation-stack I don't blame you. No worries :) Just trying to find a way to make contributing.md work. My annoyance comes from getting the same question as yours over and over.

**Comment by parro-it** [comment]
@sindresorhus [you should automate this answers](https://github.com/NARKOZ/hacker-scripts) :wink:

**Comment by automation-stack** [comment]
@sindresorhus fixed in new PR https://github.com/sindresorhus/awesome-electron/pull/145

**Comment by shinnn** [comment]
>  fixed in **new PR**

You should have read the contributing.md more carefully. https://github.com/sindresorhus/awesome-electron/blob/db0f8b98a7947beda3bcc61ce4f4972734a4cd79/contributing.md#updating-your-pr

**Pull request closed without merging**
