### PR TITLE
Add Inpad

### PR DESCRIPTION
**Pull request by Sarah-Seo**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice work on the app :)

**Comment by Sarah-Seo** [comment]
Thanks for the accepting. 👍 Have a nice day!

**Comment by zeke** [comment]
Hi @Sarah-Seo!

If you'd like to see this app on the Electron website, consider opening a PR here too: https://github.com/electron/electron-apps/blob/master/contributing.md

**Comment by Sarah-Seo** [comment]
@zeke Inpad has been listed already! Thanks for your suggesting. 🎉 
https://github.com/electron/electron-apps/pull/47

**Comment by zeke** [comment]
Oh nice. I missed it! 🎄

**Pull request merged**
