### PR TITLE
add electron-starter

### PR DESCRIPTION
**Pull request by suyash**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sorry no, I've tried this and it's absolutely horrifying to work with.

**Comment by paulcbetts** [comment]
Yo if you're gonna say something sucks (and it very may well suck, I have no illusions that I'm a node expert), maybe you can at least file an issue describing something better?

**Comment by sindresorhus** [comment]
I didn't say it sucks, only that I found it really hard to work with and it's just so much boilerplate. I guess it's subjective though. I'd rather see this happening: https://github.com/atom/electron-starter/pull/53#issuecomment-77476966

**Comment by sindresorhus** [comment]
I've actually been planning to submit some PRs to it, but I have limited time and it being in CoffeeScript makes it less of a priority for me.

**Comment by paulcbetts** [comment]
> I found it really hard to work with and it's just so much boilerplate. I guess it's subjective though. I'd rather see this happening: atom/electron-starter#53 (comment)

The idea was that it would provide you the things you needed to not only get an app running, but actually publish it / create builds on all three platforms - basically do all the shit work to launch an Electron app so that users didn't have to. Unfortunately since it's not in modules, everyone sees the shit :) 

At the time, putting that code into modules didn't make as much sense because nobody knew how to _write_ Electron apps the Right Way or how to structure a build system because the entire system was changing so rapidly, but now something more like what atom/electron-starter#53 describes is way more tenable, and I'd definitely like to see electron-starter look *way* more like that (so really it ends up being more "electron-example"). 

> I have limited time and it being in CoffeeScript makes it less of a priority for me.

Agree on that, a future version of this project will almost certainly be in ES6

**Comment by sindresorhus** [comment]
Thanks for explaining. Makes sense :)

Sorry for the unproductively criticizing comment. I'll try to find some time to open some issues/PRs.

**Comment by paulcbetts** [comment]
@sindresorhus Let's skip trying to PR the old-and-busted one, instead I'd love to get more ideas to create a new one - the strawman that's up there currently (husk-cli) is a decent start but I think we can do way better

**Pull request closed without merging**
