### PR TITLE
Add electron based clients for 1-NET service

### PR DESCRIPTION
**Pull request by webarchymeta**
The said service has various clients including ones for desktop, which currently are all developed based on electron.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you link to a place that shows some screenshots of it?

**Comment by webarchymeta** [comment]
OK, here it goes:

The entry page

The data receiving page

The file browser

The group voice chat

**Comment by webarchymeta** [comment]
Or you mean in the readme.md file? That page does not exist at present, we are working on it ...

**Comment by sindresorhus** [comment]
The list is meant to give people an impression of what's possible with Electron, like "oh wow you can do that with Electron". Not showing any screenshots at all doesn't really do that. I think I'll pass on this for now and you can try again at a later time ;)

**Pull request closed without merging**
