### PR TITLE
Add sudo-prompt

### PR DESCRIPTION
**Pull request by jorangreef**
Cross-platform `sudo`, prompting the user with a graphical OS dialog if necessary.

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is this different from [`electron-sudo`](https://github.com/automation-stack/electron-sudo), which is already in the list?

**Comment by jalcine** [comment]
It doesn't seem to be.

**Comment by jorangreef** [comment]
It's the original module which electron-sudo is based upon. It has fewer binary assets, and works as part of an asar module. Is there a restriction on having only one module per domain?

On 05 Aug 2016, at 18:51, Sindre Sorhus <notifications@github.com> wrote:

How is this different from electron-sudo, which is already in the list?

**Comment by sindresorhus** [comment]
`electron-sudo` seems to work with asar too. There's no point in including two almost identical modules.

**Pull request closed without merging**
