### PR TITLE
Add HydrogenIDE

### PR DESCRIPTION
**Pull request by facekapow**
https://github.com/facekapow/HydrogenIDE - Simple IDE for making Electron apps (in it's early stages).

### CODE REVIEW

**Comment by sbruchmann** [comment]
Please read and adhere to the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md).

- If you just created something, wait at least a couple of weeks before submitting.

**Comment by facekapow** [comment]
Oh OK.

**Comment by facekapow** [comment]
Sorry.

**Comment by ewnd9** [comment]
I've been wondering maybe all those projects which are declined should be tracked in collaborate thread https://github.com/sindresorhus/awesome-electron/issues/88 to prevent loops like "don't find a solution, start writing your own, stuck"? // cc @sindresorhus

**Comment by sindresorhus** [comment]
@ewnd9 I don't really see the point. It's a couple of weeks.

**Comment by ewnd9** [comment]
@sindresorhus hit-n-run projects may have some value and community may help to complete those projects. 

It would be nice if authors of rejected pull requests were acknowledged of possibility of help from the community

**Comment by mateothegreat** [comment]
YEa.... and abandoned projects & published libraries like to npm should have an expiration date!!!

**Pull request closed without merging**
