### PR TITLE
npm install awesome-electron

### PR DESCRIPTION
**Pull request by zeke**
:wave:

The Electron team is interested in displaying some of the contents of this amazing repository on a forthcoming version of the [electron.atom.io](http://electron.atom.io) website. This PR transforms the contents of `readme.md` into a JSON object that can be required as a node module. @sindresorhus if you like the concept, great! If not, we can publish it under a different name in a different repo.

Would love your feedback, and any ideas on how to possibly infer extra properties like `featured` and `closed_source` by reading from an element's preceding h3,h4,h5 subheadings.

cc @kevinsawicki @jlord @lee-dohm

Fixes https://github.com/sindresorhus/awesome-electron/issues/245

### CODE REVIEW

**Comment by sindresorhus** [comment]
I like the idea :)

How do you intend to keep it up to date? Any way to avoid having to do it manually? I don't want build commits in the master branch commit log. Maybe a separate branch or something.

I can add any of you to the repo if desirable.

**Comment by sindresorhus** [comment]
@lockys and @wooorm did some work in https://github.com/sindresorhus/awesome/issues/427#issuecomment-160111301, parsing the main awesome list. They might have some suggestions.

**Comment by lockys** [comment]
Yes, I parsed the links of every repos under the main awesome list for my own [project](https://github.com/lockys/awesome-search).
`awesome-electron` in JSON format is also included in [here](https://github.com/lockys/awesome.json/blob/master/repo-json/sindresorhus-awesome-electron.json).
But it seems that @zeke's parser code is better than my version :smile: 
I have no suggestions, looking forward to the forthcoming version of the `electron` website!

**Comment by wooorm** [comment]
@zeke Nice! The code you gave works, and that’s great.

If I’m allowed to nitpick, I feel it might be a bit superfluous to use marky here to transform the markdown to HTML, load that in cheerio, access it like a DOM (although the helper methods are nice!), and then generate JSON. But then of course I like remark :)

If you’re interested in trying it out and run into anything, there are [quote some docs](https://github.com/wooorm/remark/tree/master/doc), and there’s a [gitter](https://gitter.im/wooorm/remark)!

**Comment by zeke** [comment]
Thanks for the input everyone. Made a little progress:

- [x] use an array instead of a tree, inspired by https://github.com/sindresorhus/awesome/issues/427#issuecomment-160111301
- [x] discard build artifact in favor of parsing readme at require time.
- [x] eliminate runtime dependencies by parsing source markdown by hand
- [ ] add brfs module for browser support?

@sindresorhus this gets us a step closer by not requiring a build artifact, but the question of how to keep it up to date remains open...

**Comment by zeke** [comment]
I've created a branch called [npm-module](https://github.com/sindresorhus/awesome-electron/tree/npm-module), and have published the package to npm from there. I'm fine with leaving that branch open to keep master clean, and manually publishing updates as needed.

**Pull request closed without merging**
