### PR TITLE
Add electron-router

### PR DESCRIPTION
**Pull request by m0n0l0c0**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

Router component handling communication between any number of processes in electron. Bind events in any direction, from renderer to main process  and viceversa with wildcards and duplex communication, tidying ipc.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@m0n0l0c0 

> Additions should be added to the bottom of the relevant section.

**Comment by sindresorhus** [comment]
> I promise I have read the contributing guidelines twice and ensured my submission follows it.

You have not.

**Comment by m0n0l0c0** [comment]
@sindresorhus yes, I read it only once :). My fault, I was in a hurry, fixed.

**Comment by m0n0l0c0** [comment]
ping @sindresorhus

**Comment by stefanjudis** [comment]
@m0n0l0c0 still missing a period at the end I'd say. ;)

**Comment by m0n0l0c0** [comment]
Aarghh, thanks :)

**Pull request merged**
