### PR TITLE
Add Nearby Live Desktop

### PR DESCRIPTION
**Pull request by N3TC4T**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by stefanjudis** [comment]
@N3TC4T I'd say there is a period at the end missing. ;)

**Comment by N3TC4T** [comment]
@stefanjudis 
How come ?

**Comment by stefanjudis** [comment]
> Use the following format: [title](link) - Description.

**Comment by N3TC4T** [comment]
Sorry Man I don't get it , what should i change ? -_-

**Comment by stefanjudis** [comment]
You're missing a `.` at the end of your description. ;)

**Comment by N3TC4T** [comment]
Oh ok thanks :)

**Comment by sindresorhus** [comment]
Thanks for the suggestion! :) The list of open source apps is growing huge and I need to be more picky on what to include, so I'm unfortunately going to pass on this. However, I would encourage you to submit it to the official Electron apps list: https://github.com/electron/electron-apps/blob/master/contributing.md

**Pull request closed without merging**
