### PR TITLE
add Boost

### PR DESCRIPTION
**Pull request by Rokt33r**
I and my friends made this app.

The proof is here.
proof of electron app

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice work! Looks very good :)

**Comment by sindresorhus** [comment]
Your marketing text could use some work though, both in messaging and improved English. I would find someone proficient in English to look it over ;)

**Comment by Rokt33r** [comment]
In fact, I have no friend who is native English speaker because I live in Japan.. It would be very helpful!
And, I'll also try to find someone who can help it.

**Comment by sindresorhus** [comment]
If you're willing to put $5 into it, you can easily get someone to help you out here: https://www.fiverr.com/categories/writing-translation/proofreading-editing/#layout=auto&page=1 ;)

**Pull request closed without merging**
