### PR TITLE
Add SpaceRadar

### PR DESCRIPTION
**Pull request by zz85**
[SpaceRadar](https://github.com/zz85/space-radar-electron) is a disk space and memory visualization app that uses sunburst and treemap charts.

Helps understand what's taking up space on your disk drive!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice! I would rename the repo name from `space-radar-electron` to `space-radar`. It makes no sense to have Electron in the title for apps. To be entirely correct it should then be `space-radar-electron-node-chromium` :p

**Comment by zz85** [comment]
Thanks, and for the suggestion! I initially thought it's typcial to name github projects following a prefix or a suffix a technology they used, eg. node-xxx, yyy-js etc

Perhaps if I change the repo name to `SpaceRadar` or leave the name alone if it breaks old links to it?

Sorry also for the messy commit. What I thought was editing a PR description turns out to be the commit message in Github's editor... :grin:

**Comment by sindresorhus** [comment]
> Perhaps if I change the repo name to SpaceRadar or leave the name alone if it breaks old links to it?

GitHub redirects it for you.

**Comment by zz85** [comment]
> GitHub redirects it for you.

Nice! I actually went ahead and grabbed all the redirect urls :)

https://github.com/zz85/space-radar-electron-node-chromium
https://github.com/zz85/space-radar-electron-node
https://github.com/zz85/space-radar-electron
https://github.com/zz85/space-radar
https://github.com/zz85/SpaceRadar

**Comment by sindresorhus** [comment]
Lol

**Pull request closed without merging**
