### PR TITLE
Add GIFBar

### PR DESCRIPTION
**Pull request by dcrousso**
Please add my app to the Awesome Electron app listing 😄

I think this app is really useful and would benefit other users (like myself) who love GIFs (all content is from [Giffy](http://giphy.com/)) by allowing them to use them in more places than just Messenger and Slack.

Thanks!

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Nice work! Definitely gonna use this one :)

Can you fix the merge conflict? (That does not mean opening a new pull request)

Some feedback:

- Copying a link to a GIF should hide the app, as I then want to use it somewhere, and there's no reason to keep it open.
- The top-arrow over the window is not the same color as the window and looks out of place.
- There's no way to quit the app.
- I think it would have been nicer to have a settings icon in the bottom-left instead of GIFs/Stickers, that when clicked, opened a menu with: GIFs, Stickers, and Quit.
- The search field is not working like normal, for example, I can use Cmd+A to select all.
- The No Results page is not styled.

**Comment by dcrousso** [comment]
Thanks for the response @sindresorhus!

- Good idea 😃
- I had a hard time styling the arrow due to the fact that the search bar is slightly transparent.  Any suggestions?
- I realize that this isn't a valid solution, but if you open the window (via selecting the menubar icon) and hit ⌘Q, the app will quit.  I'll add something better 😛
- That is a good way to add a "Quit" button 👍
- This works just fine for me.  Can you provide steps to reproduce?
- Having the "No Results" be unstyled was actually sorta intentional, seeing as it's very rare to get to that page.  I'll see if I can add anything fun 🎉

**Comment by MarshallOfSound** [comment]
> This works just fine for me. Can you provide steps to reproduce?

It probably works in your development version and doesn't work in your packaged version due to the way `default_app` works in Electron.

**Comment by dcrousso** [comment]
@MarshallOfSound can you explain what you mean?  I haven't dealt with electron very much 😅

**Comment by MarshallOfSound** [comment]
@dcrousso When running Electron in a development instance (with `electron .`) you are actually launching the `default_app` which then loads your app.

The `default_app` has a default application that it sets for you.  When you package your application `default_app` is deleted and your app is directly launched.  This means the default menu will not be there any more.

Standard shortcuts (Select All, Copy, Paste, Etc.) come from that default menu.  So they will not work in a packaged app that doesn't set it's own menu.

**Comment by dcrousso** [comment]
@MarshallOfSound thanks for the info!  I didn't know about that 😄.  I'm finishing up finals this week, but I'll work on this over the weekend.

**Comment by sindresorhus** [comment]
> Having the "No Results" be unstyled was actually sorta intentional, seeing as it's very rare to get to that page. I'll see if I can add anything fun 🎉

This is a good inspiration: http://emptystat.es/

**Comment by dcrousso** [comment]
@sindresorhus I just added a new release ([Version 1.3](https://github.com/dcrousso/GIFBar/releases/tag/1.3)) that addresses all of your comments.  I personally like having a very minimalist "No Results" page, so I just added something kinda simple (also from [Giphy](http://giphy.com)).  I think it looks a lot better.  Thanks for the suggestions! 😄

**Comment by sindresorhus** [comment]
Looks good :)

**Pull request merged**
