### PR TITLE
Add Stacer

### PR DESCRIPTION
**Pull request by oguzhaninan**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
> By submitting this pull request, I promise I have read the contributing guidelines twice and ensured my submission follows it.

:arrow_up:

**Comment by oguzhaninan** [comment]
By submitting this pull request, I promise I have read the contributing guidelines twice and ensured my submission follows it.

**Comment by sindresorhus** [comment]
No, actually read it... The first item in bold there which you clearly did not read:

> The pull request should have a useful title **and include a link to the thing you're submitting and why it should be included.**

**Comment by oguzhaninan** [comment]
This PR adds [Stacer](https://github.com/oguzhaninan/Stacer) link to the Electron Apps part of the readme. Stacer is a ubuntu system optimizer. Thanks.

**Comment by sindresorhus** [comment]
I tried installing the app.

- It's missing an icon. It's using just the default Electron icon.
- It's missing a default window menu.
- Download and Upload reports `-0.00kb/s`. It should report `0kb/s` when nothing is going on.

**Comment by oguzhaninan** [comment]
I fixed the issues

**Comment by oguzhaninan** [comment]
I fixed the issues.

**Pull request merged**
