### PR TITLE
Add DevDocs

### PR DESCRIPTION
**Pull request by egoist**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

Repo: https://github.com/egoist/devdocs-app

### CODE REVIEW

**Comment by parro-it** [comment]
@egoist, beware that in this PR you also changed the title of the other devdocs app by @ragingwind, I suppose by mistake?

**Comment by sindresorhus** [comment]
@parro-it No, that was me, and was intentional.

**Comment by parro-it** [comment]
@sindresorhus ah ok, my apologies!

**Comment by zeke** [comment]
@egoist this is cool. You should submit it to https://github.com/electron/electron-apps, too.

**Pull request merged**
