### PR TITLE
Add WhatsApp

### PR DESCRIPTION
**Pull request by denistsoi**

### CODE REVIEW

**Comment by sindresorhus** [comment]
> If you're submitting a closed source app, include evidence of it being built with Electron.

https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

**Comment by denistsoi** [comment]
Does a screenshot with the internal package contents (unbundling with
.asar) constitute as evidence?

Can do that for you as this is how I discovered it.

On Thursday, May 12, 2016, Sindre Sorhus <notifications@github.com> wrote:

> If you're submitting a closed source app, include evidence of it being
> built with Electron.
>
>
> https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/awesome-electron/pull/260#issuecomment-218666494>
>


-- 
.

**Comment by sindresorhus** [comment]
@denistsoi Yes

**Comment by denistsoi** [comment]
*Denis Tsoi*
*Frontend Web Developer <http://www.github.com/denistsoi> | *@denistsoi
<http://www.twitter.com/denistsoi>* | +852 6183 6919*

**Comment by denistsoi** [comment]
screen shot 2016-05-12 at 3 01 06 pm

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request closed without merging**
