### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by sharpfuryz**
Added Zoommy app to Closedsource list. Zoommy is free (CC0, public domain) photo finder.
I closed previous pull-request, started this one, which could be merged without conflicts, doublechecked it.

0b5afc26-554a-11e5-9104-78e13f985e4e

### CODE REVIEW

**Comment by sindresorhus** [comment]
You're still not doing what we asked for: https://github.com/sindresorhus/awesome-electron/pull/71#issuecomment-137658244 (Please read the comment carefully).

-

*And don't open another PR. Just update this one.*

**Comment by shinnn** [comment]
> Zoommy is free (CC0, public domain) photo finder

Why is it still closed source although it's distributed under CC0?

**Comment by sharpfuryz** [comment]
Application is closed source (for this time, maybe it would be opensourced
in future) and costs 3.99$, but it searches for free CC0, public domain
photos among photostocks and photo websites.

For example: http://moveast.me/ which contains some CC0, these photos are
available in our app - each photo is checked by our moderator - written
keywords, generated meta-data and etc.

2015-09-18 0:33 GMT+03:00 Shinnosuke Watanabe <notifications@github.com>:

**Comment by shinnn** [comment]
Ah, I misread your comment.

o: Zoommy is a free-photo finder.
x: Zoommy is a photo finder and the app is free.

**Comment by sindresorhus** [comment]
ping @sharpfuryz

**Comment by sharpfuryz** [comment]
i don't understand what should i fix

2015-09-28 19:55 GMT+03:00 Sindre Sorhus <notifications@github.com>:

**Comment by sindresorhus** [comment]
i don't know how to make it clearer. gonna pass on this.

**Pull request closed without merging**
