### PR TITLE
Add electron-about-window

### PR DESCRIPTION
**Pull request by rhysd**
I created [electron-about-window](https://github.com/rhysd/electron-about-window) to provide one-stop 'About This App' window. I introduced it on some applications and it works well cross platform 😄

### CODE REVIEW

**Comment by zeke** [comment]
Wow this looks handy

**Comment by willyb321** [comment]
I've been looking for something like this for yonks now! 👍 👍 👍 from me!

**Comment by sindresorhus** [comment]
Nice :)

**Comment by rhysd** [comment]
Thank you guys :smile:

**Pull request merged**
