### PR TITLE
please add this example on splash like screen

### PR DESCRIPTION
**Pull request by saan1984**
This code shows creating a splash like screen before the main window loads.

### CODE REVIEW

**Comment by kevva** [comment]
Make it a smaller module installable through `npm` or write a blog post about it that we can link to :).

**Comment by sindresorhus** [comment]
If you need a splash screen you're doing it wrong IMHO.

**Comment by carlosperate** [comment]
Very constructive...
Nevertheless, I was wondering about this myself, what is currently the best way to achieve this?

**Comment by saan1984** [comment]
@sindresorhus, Is electron has native support for splash screen?Can you please let us know right way to develop splash screen.I will update it in my implementation.

**Pull request closed without merging**
