### PR TITLE
Add Smart Mirror

### PR DESCRIPTION
**Pull request by evancohen**
A smart mirror built to run on the Raspberry Pi. Sample video: https://www.youtube.com/watch?v=PDIbhV8Nvq8

### CODE REVIEW

**Comment by sindresorhus** [comment]
Awesome project! :)

Please read https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md
Especially this part:

> Submitted open source apps should have a English readme, screenshot of the app in the readme, and **a binary for at least one OS**, preferably OS X, Linux and Windows.

Would this be possible?

-

Can you fix the merge conflict?

**Comment by evancohen** [comment]
I suppose that I could create a binary, although may of the features would not work (for instance weather requires a custom service key and for the user to specify their location). Without writing a bunch of new code to allow the user to enter the config information in the UI it would be pretty pointless. Any chance you could make an exception?

**Comment by sindresorhus** [comment]
Sure, but I think that should be the goal regardless. Make it easy to use.

**Comment by evancohen** [comment]
Agreed! That is the end goal :)

**Pull request closed without merging**
