### PR TITLE
Add Whatsie

### PR DESCRIPTION
**Pull request by Aluxian**
> A simple & beautiful desktop client for WhatsApp Web. Chat without distractions on OS X, Windows and Linux.

https://github.com/Aluxian/Whatsie

https://whatsie.chat/

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by Aluxian** [comment]
What's missing? A screenshot in the README?

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Sun, May 22, 2016 at 12:06 PM, Sindre Sorhus < notifications@github.com [notifications@github.com] > wrote:
Please read and adhere to the contributing guidelines [about:blank] .

**Comment by sindresorhus** [comment]
Yes

**Comment by Aluxian** [comment]
Done! Is it mergeable now?

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by Aluxian** [comment]
Sure, I'll check it out.

--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Mon, May 23, 2016 at 4:43 PM, Sindre Sorhus < notifications@github.com [notifications@github.com] > wrote:
Can you fix the merge conflict?

**Comment by Aluxian** [comment]
Done!

**Pull request closed without merging**
