### PR TITLE
Add electron-menu-loader

### PR DESCRIPTION
**Pull request by ragingwind**
- electron-menu-loader

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

**Comment by ragingwind** [comment]
Sorry. I just made individual commits

**Comment by sindresorhus** [comment]
I think this module still needs some work. The API is confusing.

**Comment by ragingwind** [comment]
Would you guide me to improve that?

**Comment by sindresorhus** [comment]
Yes, but will have to wait until tomorrow.

**Comment by ragingwind** [comment]
Great. take your time. I wouldn't like to burden with you

**Comment by sindresorhus** [comment]
Alright. I've taken a real look. I think it introduces a lot of abstraction and magic without much benefit. The event stuff is useful, but I would not use the module because of all the other IMHO unnecessary abstraction. It's weird how you define the menu items, but are limited to only one custom OS menu. The documentation is also unclear and confusing. You require one menu file, but what if I want to have the menu inline, or one file for each OS.

I'm gonna pass on this as it's not something I would recommend.

You might want to consider doing only the menu event stuff as a module, but first open an issue on Electron requesting it get added to core.

**Comment by ragingwind** [comment]
Thanks for reviewing. It was aimed to solve two problems which are loading a menu on each platforms and removing boilerplate code for events. It seems to be updated to support a variety options for covering all needs about menu. And It is good idea that event stuff would be code. I will let you know if i have meaningful updates of the module

**Pull request closed without merging**
