### PR TITLE
Add stretchly

### PR DESCRIPTION
**Pull request by hovancik**
stretchly is cross-platform open source app that reminds you to take breaks when working with computer

source: https://github.com/hovancik/stretchly
hp: https://hovancik.net/stretchly/

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by Rokt33r** [comment]
> Start the description with a capital and end with a full stop/period.

Please update the description.

**Comment by sindresorhus** [comment]
Looks like a cool idea, but I think the app itself needs more work. Currently it feels more like a web app, not an actual app. Closing for now, but happy to reconsider in a few months.

---

Some feedback. For macOS, but might also apply to other platforms:

- App name should be captialized. `stretchly` => `Stretchly`.
- I would recommend reading https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/ Your app doesn't feel very native to the platform.
- Menubar icons should not be colored.
- `Quit` should be `Quit Stretchly` and also have a shortcut to quit.
- All the menu items should be titleized.
- `Settings` => `Preferences...`
- `About` should be at the bottom above `Quit`.
- There should be a separator above `Settings`.
- The `About` window is way too big, it should not be resizable, and the links there are not styled.
- Don't use a notification to inform me that Settings are saved when changed. That's just annoying.
- The `Settings` window should not be resizable.
- A lot of the text is too hard to read because it its thinness and bad contrast.
- The "buttons" in the app are not clear enough. They're just normal text without even changing the mouse pointer.
- Drop the splash screen. That's just annoying.
- Since you already have a settings window, you should move "start at login" there, to reduce stuff in the menu.
- If I click "Pause - for two hours", it should show me how much time left there is of the pause.

I know this is a lot, but I hope you take it seriously. I've been a macOS user for years and know exactly how menu bar apps should behave and look.

**Comment by hovancik** [comment]
Most of things I wont change but thanks for feedback ;]

**Comment by sindresorhus** [comment]
Too bad for your users. They'll have a subpar experience. Electron-based apps have a reputation for being slow and feel non-native. You're not helping the latter here...

**Pull request closed without merging**
