### PR TITLE
Add Nocturn

### PR DESCRIPTION
**Pull request by k0kubun**
https://github.com/k0kubun/Nocturn

Nocturn is a Twitter client maintained since the last September. Nocturn is built with not only Electron but also React and Redux. It'd be a good example to build Electron app using them.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by k0kubun** [comment]
> Can you fix the merge conflict?

Fixed in https://github.com/sindresorhus/awesome-electron/pull/217/commits/8305cc3dc41b66d5c2d3bb6d338ace4d7f61e5fd.

**Comment by sindresorhus** [comment]
The app looks really good btw. Nice work :)

**Comment by k0kubun** [comment]
Thank you :relaxed:

**Pull request closed without merging**
