### PR TITLE
Add electron-in-page-search

### PR DESCRIPTION
**Pull request by rhysd**
#**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

I created [this module](https://github.com/rhysd/electron-in-page-search) for in-page search API of `WebContents` (or `<webview>`) instance. Electron's original in-page search APIs are stateful and have some pitfalls. This package wraps them and hide complexity of APIs behind.

It's tested in all platforms using Travis CI and Appveyor. I already used this package in [my app](https://github.com/rhysd/Chromenu) and it works well.

### CODE REVIEW

**Comment by parro-it** [comment]
The link you provided point to `electron-about-window,` not `electron-in-page-search`

**Comment by rhysd** [comment]
@parro-it ah, thank you.

**Comment by sindresorhus** [comment]
> Electron exposes Chrome's native API to JavaScript. But native in-page search API has some pitfalls and stateful.

What pitfalls? The readme should answer that. It should explain what problem it solves and why I would need your package. I think you meant "statefulness".

---

It also sorely needs a better default style. I pretty much dismissed it because it doesn't look very good by default. I know that's dumb, but that's the reality. By default, I would try to match the Chrome in-page search as closely as possible, as most would probably just want a more extensible version of the default in-page search.

**Comment by rhysd** [comment]
@sindresorhus 

> What pitfalls? The readme should answer that. It should explain what problem it solves and why I would need your package. I think you meant "statefulness".

I'll describe the problem in README. And try to improve styles. After that, I'll ping you here.

**Comment by sindresorhus** [comment]
Closing for now. Let me know when it's done and I'll reopen this ;)

**Comment by rhysd** [comment]
I'm sorry for lack of response. Yeah, after fixing it, I'll create another PR again.

**Pull request closed without merging**
