### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by sharpfuryz**
I am developer of Zoommy App, and yes - it based on electron js

### CODE REVIEW

**Comment by arthurvr** [comment]
https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

**Comment by sharpfuryz** [comment]
Screenshot with app contents, which can proof that app build on top of
Electron framework

2015-09-03 18:29 GMT+03:00 Arthur Verschaeve <notifications@github.com>:

**Comment by sindresorhus** [comment]
From contributing.md:

> Start the description with a capital and end with a full stop/period.

> The pull request should have a useful title and include a link to the package and why it should be included.

-

> Screenshot with app contents, which can proof that app build on top of
Electron framework

You have to add the proof through the web UI, not email.

**Comment by arthurvr** [comment]
Ping @sharpfuryz. There's a merge conflict too.

**Comment by sharpfuryz** [comment]
ok, here is new one pull request
https://github.com/sindresorhus/awesome-electron/pull/82 , i closed
previous one.

2015-09-16 21:36 GMT+03:00 Arthur Verschaeve <notifications@github.com>:

**Comment by shinnn** [comment]
@sharpfuryz You should have pushed changes to the existing branch to update this PR, instead of opening a new one.

**Pull request closed without merging**
