### PR TITLE
Added tips for running electron-react-boilerplate on Windows 10

### PR DESCRIPTION
**Pull request by xgenvn**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

This tip will also save someone time to search for node-gyp build error, according to [this](https://github.com/nodejs/node-gyp/issues/972) and [this](https://github.com/electron/electron-rebuild/issues/15)

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Installing electron (and most modules for that matter) as global modules is in general a very bad idea and causes side effects for users who don't know what it actually does.  The boilerplate should install electron locally.

Also not many people actually use `choco` so this would cause more issues than it solves, I would see a lot of "what is choco?" issues on the horizon

We also shouldn't be recommending users go to an unstable version of `npm` which is what `npm@next` is I believe?

**Comment by xgenvn** [comment]
I added this into Tips section than Recommendation, so I think it's reasonable. And when rebuild electron using node-gyp, npm@next is necessary for vs2015 sp3.

**Comment by sindresorhus** [comment]
I appreciate the tip, but I think this should rather be added to the `electron-react-boilerplate` readme. You should also not install Electron globally.

**Comment by xgenvn** [comment]
I thought electron awesome is a place to put everything related to electron? So if there's a node-gyp error while rebuilding electron (globally or locally) we still need to search for solution in other places? I'll fix again and make another pull request.

**Comment by MarshallOfSound** [comment]
> And when rebuild electron using node-gyp, npm@next is necessary for vs2015 sp3.

That doesn't seem correct.  I am currently sitting on `npm@3.10.5` when the latest stable is `3.10.9` and I've been rebuilding with `electron-rebuild` with no issue on the latest VS2015 for months now 👍

**Comment by sindresorhus** [comment]
> I thought electron awesome is a place to put everything related to electron?

Better documented on the project where people are experiencing the issue. I'm also doubtful whether this is the correct workaround.

> I'll fix again and make another pull request.

No thanks.

**Comment by xgenvn** [comment]
@MarshallOfSound I think it's not the problem with electron-rebuild but other packages actually.
@sindresorhus Alright.

**Pull request closed without merging**
