### PR TITLE
Add electron-is-accelerator

### PR DESCRIPTION
**Pull request by brrd**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

https://github.com/brrd/electron-is-accelerator

electron-is-accelerator is a small function which checks if a string is a valid Electron accelerator.

### CODE REVIEW

**Comment by sindresorhus** [comment]
When would you need this? The readme should answer this.

**Comment by brrd** [comment]
I updated the readme. Is this clear enough:

> Check if a string is a valid [Electron accelerator](https://github.com/electron/electron/blob/master/docs/api/accelerator.md) and return a boolean. This module can be used to validate user defined accelerators before using them with [MenuItems](http://electron.atom.io/docs/api/menu-item/).

Tests have been written by @parro-it 🎉

**Comment by sindresorhus** [comment]
Makes sense. Not just `MenuItems` though. Custom shortcuts are most often used to globally toggle an app or action.

Can you fix the merge conflict?

**Comment by MarshallOfSound** [comment]
@brrd I had a quick play around and although it appears to be useful (I have user defined shortcuts) it appears to be incorrect.

For instance
```js
require("electron-is-accelerator")("A+Control") // false
```

That is a valid accelerator and should return true.  Also appears to not be able to run in a Node.JS 4.x environment due to missing `'use strict'` declarations.

**Comment by brrd** [comment]
@MarshallOfSound This is not the right place to submit issues. Please create an issue.

The "use strict" problem as been fixed today though. I still need to npm publish, I'm going to do this ASAP.

**Pull request closed without merging**
