### PR TITLE
Add electron-is-accelerator

### PR DESCRIPTION
**Pull request by brrd**
Resolve conflicts in #387

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is not the correct way to resolve a merge conflict. You resolve it in the original PR. This just cretes noise in the issue tracker...

**Comment by brrd** [comment]
Sorry for this. I actually spent half an hour looking for the way to do this, but I couldn't find it 😕
Is there a way to switch to another source branch in a PR?
If you know any clear documentation about the correct method to do this would be really helpful.

**Comment by MarshallOfSound** [comment]
@brrd To resolve conflicts normally you just need to rebase your current branch onto origins master.  I.e.

```bash
git rebase origin/master
# At this point it will fail and say "conflicts blah blah"
# You fix the conflicts in the files and stage the changes
git add changed/files
git rebase --continue
# Once the rebase is complete
# Push the updated branch to your fork
git push -f
# Then the PR will automatically update
```

**Comment by brrd** [comment]
@MarshallOfSound Okay! The `push -f` was what I missed. Thanks!

**Pull request merged**
