### PR TITLE
Add Cocos Creator. Remove close source projects: Fireball and editor-framework

### PR DESCRIPTION
**Pull request by jwu**
Since commercial reason, we have to close source for Fireball and editor-framework project. I'm very sad about this but have to do it. So I update these two projects status.

Meanwhile, a new product made by Electron coming out, and I add it, too.

### CODE REVIEW

**Comment by Pazza** [comment]
Noo! I've been working with it for the past couple of months building an app :(

**Comment by jwu** [comment]
Yeah.... it looks like I add some UNLICENSED style-sheet in editor-framework which make it illegal. I'm trying to clean the code to solve the LICENSE problem. Until that, I have to close the repo temporary.

**Comment by Pazza** [comment]
That's great news that we can expect it to come back. thank you.

**Comment by Pazza** [comment]
@jwu, any updates on when the project may become public again? Thanks.

**Comment by jwu** [comment]
@Pazza , I have a very tight schedule in my work recently, so still don't have time to process on the license problem.

**Pull request merged**
