### PR TITLE
Add PupaFM

### PR DESCRIPTION
**Pull request by xwartz**
The app based on Electron, React

### CODE REVIEW

**Comment by kevva** [comment]
:+1:

**Comment by xwartz** [comment]
@kevva Thx 😊

**Comment by sindresorhus** [comment]
Native apps are usually capitalized. I would name it `DoubanFM`.

Are you sure you can name it `douban.fm` when it's not an official app? They might have trademark on that name. The other DoubanFM app here is named `TimoFM`, probably for that exact reason.

**Comment by sindresorhus** [comment]
I would also recommend setting [this](https://github.com/sindresorhus/anatine/blob/85dbe406bf121abd0b06c8cd70335709643058ac/index.js#L47) option so the toolbar is gone on OS X. Makes it look a lot nicer.

**Comment by xwartz** [comment]
@sindresorhus  
I have renamed douban.fm to PupaFM.  And changed the toolbar style.
Thanks for your kind advice.

**Comment by sindresorhus** [comment]
Added :)

**Pull request closed without merging**
