### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by binderclip**
Add video tutorials' repo URL, may be useful :D

### CODE REVIEW

**Comment by sindresorhus** [comment]
Those are linked to from the video. I think that's enough.

In the future please use a proper commit and pull request title ;)

**Comment by binderclip** [comment]
Haha, find the repo link after SHOW ALL.

First time using pull request, next time be better ;D

By the way, the title 'Update readme.md' should be something like 'Add video tutorials' repo URL'? (despite the usefulness)

**Comment by sindresorhus** [comment]
> First time using pull request, next time be better ;D

No worries :)

> 'Update readme.md' should be something like 'Add video tutorials' repo URL'? 

Yes. I would have gone with:

> Add example project URL to the video tutorials

**Comment by binderclip** [comment]
OK, get that, thank you very much :)

**Pull request closed without merging**
