### PR TITLE
add mockingbot.com to example apps

### PR DESCRIPTION
**Pull request by plrthink**

### CODE REVIEW

**Comment by shinnn** [comment]
https://github.com/sindresorhus/awesome-electron/blob/d09b6b9c663355b9f4c68cfc0ba741387f04bfcd/contributing.md

**Comment by plrthink** [comment]
@shinnn Sorry for not providing evidence.

qq20151021-0

This is the Frameworks folder inside this app which shows it's built with electron.

**Comment by sindresorhus** [comment]
Is the app only available in Chinese? You only need the `*(Chinese)*` if it's not available in English at all.

**Comment by plrthink** [comment]
No, it supports English as well,  I should update my pr.

**Pull request closed without merging**
