### PR TITLE
add WhatsDesktop

### PR DESCRIPTION
**Pull request by mawie81**
WhatsDesktop is an unoffical WhatsApp client.

https://github.com/mawie81/whatsdesktop

### CODE REVIEW

**Comment by Qix-** [comment]
Sorry, gotta jump in here. Felt I should say something.

Although there is the MIT license under which most of Sindre's code is written, there is a bit of chivalry within the OSS community not to abuse it. Those kinds of licenses are there so people can freely use, learn from, and yes, even borrow the code in the event it's useful. The worst case scenario involves someone using a large portion of the code and modifying it a bit to suit their needs, whilst crediting either the original author or mentioning/linking to the original project.

Your repository has done neither. You basically took [Caprine](/sindresorhus/caprine), stripped off all mentions of Sindre or the original project, and now you're PRing the project back on to Sindre's list.

screen shot 2015-11-30 at 04 55 07
screen shot 2015-11-30 at 04 55 24

I'm not trying to be rude here, but there is [literally no credit whatsoever](https://github.com/mawie81/whatsdesktop/blob/55a18af5e0b2c874961fe044dcfb8d4d08890f9e/readme.md) in your readme and nothing mentioning the original project in the code. In fact, the copyright notice has even been changed. IANAL, but I'm the son of one, and I'm pretty sure that's a violation of copyright laws.

Further, this is a pretty clear violation of the [MIT License](https://en.wikipedia.org/wiki/MIT_License). Sindre [copyrighted](https://github.com/sindresorhus/caprine/blame/bb09637fc9a71fe4e07231b40fdc6214a8efa772/readme.md#L75) his code under the MIT license which fulfills this line:

> Copyright (c) 2015 Sindre Sorhus

By you ripping all of it *and* changing the copyright notice, you violated this line:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Why, then, should this be added to the list maintained by the person from whom you stole code?

**Comment by kokarn** [comment]
... wow

**Comment by mawie81** [comment]
Oh dear,

I´m sorry if I stepped on someones toes 😞. 

Yes I used Sindres code as template because both apps do basically the same: display some webpage in an electron window. 
It was never my intention to discredit or "steal" someones work. If it is looking like that then I´m deeply sorry.
I will add a credit to Caprine as soon as I´m back from work. I can understand if you dont want to merge the PR now.
Again: I´m sorry.

**Comment by sindresorhus** [comment]
We resolved this offline. Landed.

**Pull request closed without merging**
