### PR TITLE
Add evm: Electron Version Manager

### PR DESCRIPTION
**Pull request by fritx**
https://github.com/fritx/evm
based on [electron-download](https://github.com/electron-userland/electron-download)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why does it need a version manager? Electron is a local dependency in your project, not a global thing like Node.js.

**Comment by fritx** [comment]
Hey @sindresorhus, first, electron is preferred to be local dependency, but electron-prrbuilt/download does download the zip for you under ~/.electron, which could be highly reused. So evm is based on that, reusing all those versions :)

Second, electron could also be global, for those who want to start a default version of electron quickly from anywhere at terminal, just like using node ;)

**Comment by sindresorhus** [comment]
@fritx `electron-prebuilt` already handles that. If you do `npm install electron-prebuilt` or `npm install -g electron-prebuilt` it will reuse any existing Electron version in `~/.electron` if it exists.

**Comment by fritx** [comment]
Yeh, but evm is more useful as a version manager than electron-prebuilt.

`npm i -g electron-prebuilt@{ver}` = download + extract (into local project) + link
while `evm install {ver}` = download + extract (into just ~/.electron)
`evm use {ver}` = link (no need to fetch from npm again)
Also, `evm ls` could list the all the versions user can switch to, just like [nwjs](https://github.com/egoist/nwjs#nwjs--).

Some people develop some local electron apps, and usually open them just using global electron, then evm is useful to them.
Installing too many local electrons separately sometimes would be a little annoying and unnecessary.
Maybe electron-packager, etc, could use electrons extracted under ~/.electron instead?

I guess it could save more disk space & more npm fetching. 😃

**Comment by fritx** [comment]
Just want to polish the commit msg (push -f) since it's not yet merged, but the PR is gone...

**Pull request closed without merging**
