### PR TITLE
Adding Traverse to app list.

### PR DESCRIPTION
**Pull request by jasonraimondi**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

Adding [Traverse](https://github.com/jasonraimondi/traverse), a tool to browse trending Github repositories.

### CODE REVIEW

**Comment by jasonraimondi** [comment]
Bumpsy

**Comment by sindresorhus** [comment]
Got this on the first launch:

screen shot 2019-02-18 at 15 26 14

**Comment by sindresorhus** [comment]
The app works fine, but the UI could use more work. The titlebar font is too large. I have no idea what the top-left buttons do. The left sidebar is missing a scrollbar. The username part of the repo title should also be clickable. The purple header color is too much and makes the app look bad.

**Comment by sindresorhus** [comment]
The icon also looks broken:

screen shot 2019-02-18 at 15 36 16

It looks cutoff and white is usually not a good background color for app icons.

**Comment by sindresorhus** [comment]
I also fail to see the use-case for this app over just using https://github.com/trending The readme should sell the app better and answer this.

**Comment by sindresorhus** [comment]
Closing for now, but happy to reconsider it in the future when the app has had some more time to mature :)

**Comment by sindresorhus** [comment]
However, I would encourage you to submit it to the official Electron apps list: https://github.com/electron/electron-apps/blob/master/contributing.md

**Comment by jasonraimondi** [comment]
Thanks for the honest feedback! Appreciate it. 

I agree the UX/UI could also needs a lot of love, although my biggest concern is the actual error posted. 

It has been a little side project for fun to see what electron is all about. 

Sorry for having you review an unfinshed piece.

**Pull request closed without merging**
