### PR TITLE
Add Nes

### PR DESCRIPTION
**Pull request by yasaricli**
Emulator of NES written in javascript for electron.

### CODE REVIEW

**Comment by zeke** [comment]
This looks awesome! But @sindresorhus likes to let things bake a bit first. See CONTRIBUTING.md:

> If you just created something, wait at least a couple of weeks before submitting.

**Comment by yasaricli** [comment]
@zeke hey thanks; I've built all platforms and add to readme file Screenshot; waiting :+1:

**Comment by sindresorhus** [comment]
Ping me here when it's time and I'll reopen ;)

**Comment by sindresorhus** [comment]
- Add a direct download button to the readme
- Mention what it uses for the actual emulation and link to it: https://github.com/jpikl/cfxnes
- CC0 is not a good code license. Use MIT instead.

-

To be honest though. It probably won't be accepted in its current form as it's pretty much just [`cfxnes`](https://github.com/jpikl/cfxnes) wrapped in Electron with a button to open a rom. Put some more work into it. From the `cfxnes` readme it says it supports fullscreen, so I would implement support for that. Right now the output is very tiny. Add some config like ability to set keybindings and gamepad. Maybe add a game library of some kind, [example](http://openemu.org/), with thumbnails. Add a [proper menu](https://github.com/sindresorhus/caprine/blob/master/menu.js) template with ability to restart/pause/stop the game. Etc.

**Comment by yasaricli** [comment]
@sindresorhus I will make them soon. thanks :+1:

**Pull request closed without merging**
