### PR TITLE
Add tweet-rec

### PR DESCRIPTION
**Pull request by midnightSuyama**
tweet-rec is open source, tweet recording player by electron.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by midnightSuyama** [comment]
Noted, added screenshot to the readme.

**Comment by sindresorhus** [comment]
From looking at the readme, while the app looks nice, I still have no idea what the app does and why I would want it. The readme should be a marketing page. Sell it. And describe what it does and why I would want it, and what problem it solves.

**Comment by midnightSuyama** [comment]
Right! It added the following.

> Usually, you will not be able to watch a live tweet of the program when play a TV program and radio program which recorded.
> This application reproduce a live tweet by playing the recorded program at the same time.

and

> ## Features
>
> * Record tweet with hashtag to CSV file
> * Play tweet like a live from CSV file

Thanks:)

**Pull request merged**
