### PR TITLE
Add Buka

### PR DESCRIPTION
**Pull request by oguzhaninan**
https://github.com/oguzhaninan/Buka

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm not comfortable including something that requires downloading from Sourceforge. Sourceforge is known bad site: https://www.howtogeek.com/218764/warning-don%E2%80%99t-download-software-from-sourceforge-if-you-can-help-it/

**Comment by oguzhaninan** [comment]
What should I do. If I remove the connection, will it fix the problem?

**Comment by sindresorhus** [comment]
Yes, you're already hosting the binaries on GitHub. So I don't even see the point of the link.

**Comment by oguzhaninan** [comment]
I removed the link.

**Comment by Rokt33r** [comment]
@oguzhaninan This is all what you need. https://help.github.com/articles/creating-releases/

**Comment by oguzhaninan** [comment]
Is there another problem?

**Pull request merged**
