### PR TITLE
Add Abricotine

### PR DESCRIPTION
**Pull request by brrd**
> Abricotine is an open-source markdown editor built for desktop.

https://github.com/brrd/Abricotine

### CODE REVIEW

**Comment by sindresorhus** [comment]
I dig the inline preview :)

**Comment by brrd** [comment]
> I dig the inline preview :)

Hmm... Well, this may be an approximate translation of mine. I call the preview "inline" because it's displayed within the edited content. But there's probably a clearer way to say it... It's open source, so feel free to change it if you find better words, of course ;)

Thanks for merging indeed!

**Comment by sindresorhus** [comment]
Not sure what you think I said, but I meant, I like the inline preview feature :)

**Comment by brrd** [comment]
Ok, so *this* was my translation mistake ;)
Thanks!

**Pull request merged**
