### PR TITLE
Added is-electron

### PR DESCRIPTION
**Pull request by delvedor**
*Added 'is-electron' library under 'Tools' section.*
_______________________________________________________________________
**Description:**
An 'is' utility for Electron.
[is-electron](https://github.com/delvedor/is-electron) provides a set of isomorphic 'is' APIs, that you can use it both in main and renderer process.

**Why it should be included:**
I think it can be a useful tool, it's pretty handy and makes the code easier to read.

*Ps: I hope you find it useful, I'm open to suggestions and improvements!*

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good start. Some feedback:

- I would go with electron as a prefix to match other packages: `electron-is`.
- `is.mac()` should be `is.osx`. Mac is the hardware, not the OS name.
- I would try to be consistent of the naming of `is.ia32()` and `is.x64()`.
- `is.production()` - How can this even be set in production? NODE_ENV is set locally, not in your packaged app. You might want to check out: https://github.com/sindresorhus/electron-is-dev and inverse it.
- You don't have to hardcode https://github.com/delvedor/is-electron/blob/0cd53836c864e690818f3edc562679ffd98a1993/is.js#L15 Notice how the `10.X` is always 4 behind the first number in the Darwin release. See: https://github.com/sindresorhus/osx-release/blob/8edbc69a5dd9d2e062cf6e0e16559f6b7b882dbf/index.js#L19-L22

**Comment by delvedor** [comment]
@sindresorhus, given that is a new package I can rename it without too much problems, I read that the suggested solution is to `npm deprecate` the old package and add a console.log that points to the new package and obviously publish it.

By consistent on naming *ia32* and *x64*, you mean rename *ia32* to *x86*?
Thanks for all the other suggestions! :)

If it's ok for you, now I make all the "fixes" and then update the pull request.

**Comment by sindresorhus** [comment]
> I read that the suggested solution is to npm deprecate the old package and add a console.log that points to the new package and obviously publish it.

No need for console.log. Just `npm deprecate is-electron 'deprecation message'`.

> By consistent on naming ia32 and x64, you mean rename ia32 to x86?

Yes

> If it's ok for you, now I make all the "fixes" and then update the pull request.

👍

**Comment by delvedor** [comment]
I did all the changes you suggested except for the osx releases part, I will do later that.

I'm sorry but I made a little mess and I've opened another pull request #264 with my changes.

**Pull request closed without merging**
