### PR TITLE
Add SkelEktron

### PR DESCRIPTION
**Pull request by vtardia**
SkelEktron is an application template with some handy features like smart logging, support for electron builder and build targets.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Looks good, but IMHO a bit too much boilerplate. Especially all the printer stuff. Very few apps would need printing ability. That should be a recipe or something, not tightly integrated in the boilerplate...

Some feedback:

- https://github.com/BZCoding/SkelEktron/blob/eb2f9762c0c028d311dddb56e1d74c57c2466d54/app/main.js#L142 Ugh, this is not a good default. The beauty of the Electron auto-update functionality is how it *just works* silently. Think Chrome. Don't bother users with a prompt.
- https://github.com/BZCoding/SkelEktron/blob/eb2f9762c0c028d311dddb56e1d74c57c2466d54/app/main.js#L72 This can just be `title: app.getName(),`
- The [menu](https://github.com/BZCoding/SkelEktron/blob/eb2f9762c0c028d311dddb56e1d74c57c2466d54/app/lib/menu.js) is outdated (https://github.com/electron/electron/releases/tag/v1.2.5, see first item) and incorrect and doesn't take into account platform differences. See https://github.com/sindresorhus/anatine/blob/master/menu.js for how to correctly implement a cross-plaform menu.
- https://github.com/BZCoding/SkelEktron/blob/eb2f9762c0c028d311dddb56e1d74c57c2466d54/package.json#L17-L48 Ugh, way too much.

**Comment by vtardia** [comment]
Hi @sindresorhus,

thank you for the feedback. I've made the printer module optional and improved first 3 points. About the last... well, it's a template, you can remove what you don't need ;)

**Comment by sindresorhus** [comment]
Different views I guess. I would never use something where I inherit thousands of lines of code before I've even started coding the app.

-

The menu is still highly inaccurate. I've spent countless hours perfecting the menu in https://github.com/sindresorhus/anatine/blob/master/menu.js I would recommend taking a close look. There are a lot of subtle platform differences.

**Comment by sindresorhus** [comment]
Landed :)

**Pull request closed without merging**
