### PR TITLE
Add MSI Keyboard LED Controller

### PR DESCRIPTION
**Pull request by stevelacy**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion! :) The list of open source apps is growing huge and I need to be more picky on what to include, so I'm unfortunately going to pass on this. Keep up the great work though.

**Comment by stevelacy** [comment]
Interesting. Any explanation to why This particular commit or project is objectionable?
Just been picky starting now is odd.

**Comment by sindresorhus** [comment]
Tiny target audience for the app. Doesn't use Electron much. More of a webapp wrapped in Electron. The list of open source apps is mainly meant to be a resource for users to see how people use the Electron API's and what's possible.

**Comment by stevelacy** [comment]
I would appreciate those details added to the contribution guidelines, it would have saved me opening this PR.

**Pull request closed without merging**
