### PR TITLE
Add Inboxer

### PR DESCRIPTION
**Pull request by denysdovhan**
This PR will add Inboxer to the list of Electron apps.

### Links

**Repo:** https://github.com/denysdovhan/inboxer
**Website:** https://denysdovhan.com/inboxer
**Publication on Medium:** https://medium.com/@denysdovhan/inboxer-1-0-0-is-out-ce1521c1e5bf 

### Rules

* **Don't use another company's trademarks**: Inboxer has a [Disclaimer](https://github.com/denysdovhan/inboxer#disclaimer) which let users know:
  > This code is in no way affiliated with, authorised, maintained, sponsored or endorsed by Google or any of its affiliates or subsidiaries. This is an independent and unofficial Inbox by Gmail app. Use it at your own risk.
* **If you just created something, wait at least 20 days before submitting.** Yes, I waited for awhile, release few new versions and made some features.
* **Submitted open source apps should have a readme, screenshot of the app in the readme, and a binary for at least one OS, preferably macOS, Linux and Windows.** Yes, it has `README.md` and signed binaries for all supported platforms.
* **Keep descriptions short and simple, but descriptive.** It clearly describes the purpose of app.

### Logo

icon

#### macOS

inboxer-mac-desktop

#### Linux

inboxer-linux-desktop

#### Windows

inboxer-windows-desktop

### CODE REVIEW

**Comment by sindresorhus** [comment]
Great that you could find some inspiration from [Caprine](https://github.com/sindresorhus/caprine), but more than 50% of the codebase is from Caprine, so would be appropriate to follow the MIT license.

**Comment by sindresorhus** [comment]
Also please read the contribution guidelines. New entries should be added to the bottom of the relevant section.

**Comment by denysdovhan** [comment]
I've moved Inboxer to the end of the section.

> Great that you could find some inspiration from Caprine, but more than 50% of the codebase is from Caprine, so would be appropriate to follow the MIT license.

Yes, thanks for an amazing application. Personally, I use it every day. However, I used not only Caprine for inspiration, but also these apps:

* [Ramme](https://github.com/terkelg/ramme) by [Terkel Gjervig Nielsen](https://github.com/terkelg)
* [Keep](https://github.com/andrepolischuk/keep) by [Andrey Polischuk](https://github.com/andrepolischuk)

I've listed them in `README.md` beside the Caprine. Also, I've mentioned that all of them under the MIT license. As I know, that should fit the requirements of MIT license. Please, correct me if I'm wrong.

**Comment by denysdovhan** [comment]
Yay! Thanks!

**Pull request merged**
