### PR TITLE
Add electron-settings to Tools

### PR DESCRIPTION
**Pull request by nathanbuchar**
[electron-settings](https://github.com/nathanbuchar/electron-settings) is a simple persistent user settings manager, originally adapted from Atom's own internal configuration manager. It was also just recently adopted as the settings manager of choice for Github's [demo Electron app](https://github.com/electron/electron-api-demos).

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
How is it any different/better from the existing settings modules in the list? There are already multiple.

**Comment by nathanbuchar** [comment]
Ah yes, a good point.

Electron-settings was one of the first settings modules available for Electron, I just never knew this repo existed! As I mentioned, it was originally adapted from Atom's internal configuration manager, so it uses the concept of "key paths" to set properties, essentially dot notation to traverse a JSON tree. `settings.set('foo.bar', 'baz')`, for example. This concept has since been adapted by electron-config. Conversely, with electron-json-storage you can only set a flat list of keys—kind of like local storage. Each of these keys are then stored in a different file in your app's user data folder. 

One thing that I think sets it apart—and what I like most about it—is that, like with Atom's config module, you can watch key paths for changes. Take the following for example:

```js
settings.watch('foo', newValue => {
  console.log(newValue); // "new"
});

settings.set('foo', 'new');
```

Here I set up a key path observer on `"foo"`, then I change its value. This change is caught and the change handler is called with the old and new values passed in as arguments. This system allows you to modularize your application with a bit more freedom. With Atom for instance, packages can watch for core settings changes on their own and handle them accordingly without having to hook in with Atom's core directly :)

**Comment by sindresorhus** [comment]
> This concept has since been adapted by electron-config.

Not really. I made `electron-config` with support for key-paths as I already had found it useful many times in the past.

**Comment by sindresorhus** [comment]
Thanks for elaborating :)

**Comment by nathanbuchar** [comment]
You're right, that was a bad choice of words! Meant to say that electron-config used the same system, not to imply that the concept was influenced by electron-settings. Thanks for the merge :)

**Pull request merged**
