### PR TITLE
Add RunJS

### PR DESCRIPTION
**Pull request by lukehaas**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-electron/blob/main/contributing.md

**Comment by lukehaas** [comment]
Thanks @sindresorhus I read the guidelines.
Regarding the evidence of Electron, apologies, I thought this would be clear from the website link.
Further proof of this can be. seen in the docs of the app: https://runjs.app/docs.

**Comment by sindresorhus** [comment]
> Further proof of this can be. seen in the docs of the app: https://runjs.app/docs.

There's no mention of Electron there.

**Comment by lukehaas** [comment]
I see, but the guidelines only ask for evidence of Electron, wasn't sure how extensive this needs to be. 
The RunJS docs state the Node, Chromium and V8 versions that it runs against, which match the Electon versions.

Further evidence is the entry  in the official Electron app list: https://www.electronjs.org/apps/runjs

**Comment by sindresorhus** [comment]
> The RunJS docs state the Node, Chromium and V8 versions that it runs against, which match the Electon versions.

That is an assumption, not evidence.

> Further evidence is the entry in the official Electron app list: https://www.electronjs.org/apps/runjs

That is good enough for me.

**Pull request merged**
