### PR TITLE
Add site for electron based clients for 1-NET service

### PR DESCRIPTION
**Pull request by webarchymeta**
The said service has various clients including ones for desktop, which currently are all developed based on electron. The front page of the current site contains a list of screenshots that correspond to major features of the current clients.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/awesome-electron/pull/355.

**Comment by webarchymeta** [comment]
@sindresorhus Well, are you going to consider my request by reopening #355?

**Comment by webarchymeta** [comment]
@sindresorhus I have added the screenshots, as you sugguested ...

**Comment by sindresorhus** [comment]
> I think I'll pass on this for now and you can try again at a later time ;)

At a later time doesn't mean a couple of days later, but I guess I should have been clearer.

-

I'm mostly passing on this as it doesn't really show what's possible with Electron. The app looks more like a web app wrapped in a browser. It even has a refresh and back/forward buttons. Native apps doesn't work like that.

**Pull request closed without merging**
