### PR TITLE
Blox Party no longer uses Electron

### PR DESCRIPTION
**Pull request by kvnneff**

### CODE REVIEW

**Comment by zeke** [comment]
@kvnneff what does it use now instead?

**Comment by caioproiete** [comment]
@zeke it uses [Deku](https://github.com/dekujs/deku) now

**Comment by kvnneff** [comment]
Well I changed the description to say Blox Party was made using Deku which is just a React-like framework.  But as for running the app it now just runs in a browser.  I ended up not using Electron for anything but rendering pages.

**Comment by caioproiete** [comment]
@kvnneff you may want to change the description of the repo as well

image

**Pull request merged**
