### PR TITLE
Added pack electron with gulp video

### PR DESCRIPTION
**Pull request by ThorstenHans**

### CODE REVIEW

**Comment by shinnn** [comment]
Your sample code uses [gulp-run](https://github.com/gulpjs/plugins/blob/847d4be9b84ec2a30e3d8012b12088101d2c094d/src/blackList.json#L111) and [gulp-clean](https://github.com/gulpjs/plugins/blob/847d4be9b84ec2a30e3d8012b12088101d2c094d/src/blackList.json#L6) both of which has been blacklisted.

**Comment by ThorstenHans** [comment]
mehh, okay will re-record that :+1: thanx for the advice haven't seen the blacklist yet.

**Comment by sindresorhus** [comment]
You're not really packaging, you're just compiling ES6 and the asar archive. This is the easy part. The boilerplate and screencast should include https://github.com/maxogden/electron-packager

**Comment by ThorstenHans** [comment]
Thanks for the feedback. Will look into that and investigate more time in it. It's a little bit hard to find all those cool packages out there for electron because of the rebrand. Would be great to see all those electron related packages also appear in the list, not only the yeoman generators

**Pull request closed without merging**
