### PR TITLE
Pixitron quick start for game designers

### PR DESCRIPTION
**Pull request by h3rb**
Take another look, it's actually much more than just a clone of electron-quick-start... fyi i plan to evolve and expand it

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Duplicate of #534

**Comment by sindresorhus** [comment]
> it's actually much more than just a clone of electron-quick-start

I didn't say it was a clone of electron-quick-start, I said the Electron parts were just that. There's very little Electron specific logic in there. You're pretty much just using Electron as a browser. Your template could be used in the browser with just tiny changes.

> fyi i plan to evolve and expand it

That's great, but I review based on what's there today.

**Comment by sindresorhus** [comment]
I'm sure this is a great starting point for creating Pixie-based games, but it's not really showing off anything unique with using Electron.

**Comment by h3rb** [comment]
Well, since you haven't included it in the boilerplates list, it's less likely people will see it or be able to use it.  I originally created it for myself alone but wanted to share it because it is a good way to expose people to both Pixi and Electron and Node if they are game designers.  The reason I spent about 10 hours making it was that I did not see anything like it in the list, and I was inspired by the following statements which lead me to your repo and my attempt to include it, which I still don't think shouldn't be included.  In fact, I'm a bit disappointed it's not included. 

"**Electron development is un-opinionated - there is no "one true way" to develop, build, package, or release an Electron application.** ... that all developers working with Electron, both big and small in team-size, are never restricted in what they can or cannot do at any time during their development lifecycle. However, for many developers, **one of the community-driven boilerplates or command line tools might make it dramatically easier to compile, package, and release an app**.

Boilerplate vs CLI
**A boilerplate is simply a starting point - a canvas, so to speak - from which you build your application. They usually come in the form of a repository you can clone and customize to your heart's content.**"

Since electron-quick-start was so useful, I figured making a game development starting place would also be useful.  But, I guess you don't agree and you're the judge and jury of what's Electron, so...

**Comment by h3rb** [comment]
"Your template could be used in the browser with just tiny changes."  You'd want that.  Because if you're a game designer, you want it to work in the browser or in Phonegap or equivalent cross-platform mobile developer because Electron doesn't handle mobile.  You wouldn't want to limit yourself to just PC games, especially since Electron is essentially a CEF browser, I'm not seeing the point of what you are saying.

**Comment by groundwater** [comment]
Hi 👋 . Chiming in because of this https://twitter.com/LAGameStudio/status/987733461774499845 and other email correspondence sent to the Electron team.

@h3rb this repository is a community-run collection of curated Electron apps. The ElectronJS team is not involved in the selection/rejection process.

**Comment by h3rb** [comment]
Well, I guess ElectronJS team has nothing to do with ElectronJS.org then?  Look it's fine and dandy that someone wants to reject my contribution, but it's not clear where the line is drawn between "team" and "website", "boilerplate" and "electronjs", "starting place" and "fully implemented" or "unique" and "not unique enough" ... definitely don't see the value in someone basically rejecting contributions that could have lead to more users.  Will update tweet to reflect your claims, groundwater.

**Pull request closed without merging**
