### PR TITLE
Add Markdownify

### PR DESCRIPTION
**Pull request by amitmerchant1990**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm unfortunately gonna pass on this. There are already many Markdown apps in the list.

**Comment by amitmerchant1990** [comment]
@sindresorhus Although you had turned down my pull request for the said reason, you have recently accepted the similar application. May I know why? You can check here : https://github.com/sindresorhus/awesome-electron/pull/308

**Comment by amitmerchant1990** [comment]
Waiting for your response. @sindresorhus

**Comment by amitmerchant1990** [comment]
You have lost my respect @sindresorhus

**Comment by jdfwarrior** [comment]
I don't think this is quite serious enough to get upset to take it personally.  Maybe he just changed his mind

**Comment by sindresorhus** [comment]
@amitmerchant1990 I don't always have the time to answer right away. It's summer now. Stop being so demanding 😎. I passed on yours since it didn't really improve upon any of the existing entries. [Marky](https://github.com/vesparny/marky) does. It uses a proper app structure and framework and not a bunch of spaghetti code. The open source section is meant to be a list of apps people can learn from, and I want to show them the best. That means being a little picky about what to include, especially when there are many apps trying to solve the exact same problem.

**Pull request closed without merging**
