### PR TITLE
Added new articles

### PR DESCRIPTION
**Pull request by akashnimare**
Added two new articles which mainly covers creating installers and adding autoupdates in electron app.

- [A complete guide to packaging your Electron app](https://medium.com/@meakaakka/a-complete-guide-to-packaging-your-electron-app-1bdc717d739f)
- [How to add auto-updates to your Electron application: An up to date guide](https://medium.com/@meakaakka/how-to-add-auto-updates-to-your-electron-application-an-up-to-date-guide-d62794a0467d)

**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. **

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by sindresorhus** [comment]
It's not the days. There are multiple things not adhering to the contributing guidelines.

**Comment by sindresorhus** [comment]
The articles are too short to include here right now. You titled the first one "A complete guide to packaging your Electron app", but where is the "complete" guide. It's more like a super quick overview with some sample code without any explanation of that code. It also covers the easy part of packaging. The hard part is setting up something that runs on a CI and automatically builds for all systems and uploads to GitHub Releases when done.

**Comment by akashnimare** [comment]
@sindresorhus yeah, I think I should have included "automatically build on CI" part. No worries; I'll update it with some more detail and code explanations as well 😄 
Btw what else should I include in the second [article](https://medium.com/@meakaakka/how-to-add-auto-updates-to-your-electron-application-an-up-to-date-guide-d62794a0467d)?

**Comment by sindresorhus** [comment]
> Btw what else should I include in the second article?

I would explain the code better, not just code dump and tell the user this is how it's done. There are many typos in the articles and code comments btw. Maybe point to some good real world examples, like the auto-updating in Hyper.app and WebTorrent.app. I also don't think you set a good precedent by having an intrusive modal on every update. I would personally prefer silent updates like Chrome does it, but it should maximum be something more unintrodusive like Hyper.app does it (small inline notifications). I would also try to cover how you actually make the update available (which would be a continuation of the previous article of setting up building on Travis).

**Comment by akashnimare** [comment]
@sindresorhus thanks for the review. I've recently started writing so I don't have much experience on what exactly to write 😆  I'll be adding all those points you mentioned 🙌

**Pull request closed without merging**
