### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by garrylachman**
added ElectroCRUD

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by garrylachman** [comment]
Hi,
I read the guidelines, you can check my project at github and the mini site here: http://garrylachman.github.io/ElectroCRUD/.

Thanks

**Comment by garrylachman** [comment]
?

**Comment by sindresorhus** [comment]
This:

> The pull request should have a useful title and include a link to the package and why it should be included. - https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md

-

Also no need to ping after only a few days. This is open source. I do it in my free time when I can.

-

I have reviewed your app and decided to pass on it. The list of open source apps is meant to be a useful resource for users to see how Electron is used in the wild and learn from it. From looking at your app code, it's pretty much just a web app wrapped in Electron. The only Electron API usage I could find is the normal window boilerplate: https://github.com/garrylachman/ElectroCRUD/blob/master/app/index.js Thanks for the suggestion though :)

**Pull request closed without merging**
