### PR TITLE
Add Telegram chat (Russian) to Community section

### PR DESCRIPTION
**Pull request by LestaD**
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better. 🖖**

https://telegram.me/electron_ru

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why Telegram? I don't think open source communities should require an app to work. I don't have Telegram, so I can't even confirm this is something worth adding.

**Comment by LestaD** [comment]
@sindresorhus you can open web.telegram.org

**Comment by DenisIzmaylov** [comment]
Telegram is the new space for russian-speaking communities and communication. It works much better than Slack, Gitter or other "isolated" rooms.

+ http://fortune.com/telegram-pavel-durov-mobile-world-congress/

In a few words - Telegram is like Skype but for texting.

@sindresorhus, at the moment russian-speaking community is migrating from Slack and Gitter to Telegram. We have a lot of russian-speaking groups here about JavaScript:

+ https://www.telegram.me/react_js (1350+ members)
+ https://telegram.me/nodejs_ru (980+ members)
+ https://telegram.me/angular2 (450+ members)

**Comment by gaearon** [comment]
FWIW—I don’t participate in group chats because they’re too noisy.
But I can confirm Telegram is insanely popular in Russia.

**Comment by DenisIzmaylov** [comment]
Dan, sorry, just did not track your membership in the group. My fail. Just saw you've been here. Thanks for confirmation!

**Comment by DenisIzmaylov** [comment]
Thank you very much!

**Pull request merged**
